---
- hosts: all
  tasks:
  - name: Install required packages for Docker
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
      update_cache: yes

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

  - name: Install Docker CE
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      update_cache: yes

  - name: Enable container logging to Docker host
    copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
           "log-driver": "syslog",
           "log-opts": {
           "syslog-address": "unixgram:///dev/log",
           "tag": "docker/{{ '{{' }}.Name{{ '}}' }}"
           }
        }

  - name: Restart Docker service
    ansible.builtin.service:
      name: docker
      state: restarted
      enabled: true